name: release-gate

on:
  push:
    # auto trigger when a new cave version is released
    tags: ['v*']
  workflow_dispatch:

jobs:
  verify-samples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show workspace after checkout
        run: ls -la

      - uses: ./.github/actions/setup-node-env
        with:
          working-directory: ./clean-architecture-visualizer

      - name: Build the CLI and frontend
        run: npm run build
        working-directory: ./clean-architecture-visualizer

      - name: pack then install package
        run: npm pack && npm install -g ./*.tgz
        working-directory: ./clean-architecture-visualizer

      - name: check cave version
        run: cave --version

      - name: checkout samples
        uses: actions/checkout@v4
        with:
          repository: CA-Visualizer-for-Education/cave-test-repo
          path: cave-test-repo
          ref: 7bc27be55ef296ebb55cf85d34380c4ca0afe765

      - name: Show workspace after checking out test repo
        run: ls -la
        working-directory: cave-test-repo

      # call run script that verifies all sample projects
      - name: Verify samples
        working-directory: cave-test-repo/violation-bad-import
        run: node scripts/release-gate/run.mjs --samples "$GITHUB_WORKSPACE/cave-test-repo"
